mit-dci/CryptoKernel

- installdeps.sh
A vanilla Ubuntu install requires `sudo ldconfig` after the openssl install or else one gets this error:
```./ckd: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory```
> Add ldconfig to installdeps.sh

- src/client/rpcserver.cpp
- src/client/wallet.cpp
- src/client/wallet.h
Modified wallet.h, wallet.cpp, and rpcserver.cpp
In the wallet.cpp watchFunc, I filter the unconfirmed transactions to the ones that correspond to the wallet. Those transactions can be viewed through the listTransactions rpc function. They contain a key value pair "unconfirmed" : true, to signify that they are not yet on the blockchain.
> Added unconfirmed transaction tracking in the wallet

- src/kernel/log.cpp
When running in a service manager which captures STDOUT, output is batched until the buffer fills therefore preventing realtime capture. This flushes on each write.
> Add flush to each line logged

- tests/StorageTests.cpp
Storage tests have been broken since the constructor format was changed in #26
> Fix storage tests compilation

- build/macos/Dockerfile
Previously we `git clone`'d so were always building master.
> Use locally provided CK source for macOS build

- src/kernel/storage.cpp
FastWriter and StyledWriter have been deprecated by upstream libjsoncpp. Switch to the recommended StreamWriterBuilder instead and manually specify our desired Json stringify style. For classes like Blockchain which keep a Storage poiner around all the time, we should refactor to uses a shared rather than static writer object to save time when writing Json to string.
> Stop using deprecated methods from libjsoncpp

- Makefile
- src/kernel/storage.cpp
- tests/BlockchainTypesTests.cpp
- tests/BlockchainTypesTests.h
When we replaced FastWriter with StreamWriterBuilder the output format changed (neglecting a trailing newline) and thus blockchain type IDs changed. Since that's consensus critical the new toString code needs to produce the same format string. Add a unit test to catch regressions.
> FastWriter used to add a newline to output, new code should do the same

- installdeps.sh
When running `installdeps.sh` on Ubuntu 18.04, the line that does `cd libmicrohttpd*` will fail with 
```
./installdeps.sh: line 18: cd: too many arguments
```
Removing the .tgz after unpacking it fixes this issue for me.
> Fixes installdeps issue on Ubuntu 18.04

- src/client/rpcserver.cpp
- src/kernel/blockchain.cpp
- src/kernel/blockchain.h
This PR adds the the "creationTx" flag to outputs so that outputs have a back pointer to what transaction derived it.
> add creationTx flag to outputs

- src/kernel/blockchain.cpp
- src/kernel/blockchain.h
- src/kernel/network.cpp
- src/kernel/network.h
- src/kernel/storage.cpp
- src/kernel/storage.h
Previously lock contention was very high while the blockchain was syncing. This meant many RPC calls would timeout. Instead make use of leveldb snapshots and peerInfo caching internally to the blockchain and network to prevent waiting on several locks. This is at the cost of slightly stale data from RPC.
> Implement a read-only storage transaction and cache peerInfo for RPC

- src/kernel/blockchain.cpp
- src/kernel/blockchain.h
- src/kernel/consensus/regtest.cpp
- src/kernel/consensus/regtest.h
- tests/BlockchainTests.cpp
- tests/BlockchainTests.h
- tests/BlockchainTypesTests.h
We don't catch `Json::Exception`s in verifyTransaction so we must check if the `signature` input data field or `schnorrKey` output data field are not strings otherwise one can cause a node to crash. Added a unit test for this eventuality to catch regressions.
>  Check for malformed signature and schnorrKey fields in verifyTransaction 

- src/kernel/blockchain.cpp
- src/kernel/consensus/regtest.cpp
- src/kernel/storage.cpp
- src/kernel/storage.h
- tests/BlockchainTests.cpp
- tests/BlockchainTests.h
Previously to keep track of the map of `publicKey`s to unspent and spent outputs we used a JSON array with one key per public key. If a given public key was used many times, this would lead to a very large JSON object being retrieved from and saved to the database for every output using that public key. This lead to cache misses and large wait times for database operations.
Instead, play to leveldb's strengths by using one key per output and retreiving the list of outputs for a public key using an iterator. This means the speed to update the public key/output map is now almost constant rather than linear with the number of outputs associated with a public key.
The PR also adds a unit test for basic `getUnspentOutputs` functionality.
> Improve transaction commit speed by changing the publicKey index method

- Dockerfile
Added a dockerfile that runs the `installdeps.sh` and builds. It uses ckd as the main entrypoint.
You can use this by first running:
`docker run --name cryptokernel -ti {image tag}`
and then in another terminal you can do:
`docker exec -ti cryptokernel /app/bin/ckd getinfo`
> Docker container for ckd

- build/linux/Dockerfile
- premake5.lua
This prevents the Linux static binary from syncing up as it's unable to verify Lua scripts. The solution was the build the linux target for Lua and compiling ckd with rdynamic.
> Fix bug where lz4 couldn't be loaded with the linux static build

- src/kernel/network.cpp
- src/kernel/networkpeer.cpp
- src/kernel/networkpeer.h
Remove mutex protecting `sf::TcpSocket` (turns out we probably don't need it and can have blocking socket calls instead of looping). This results in a decent reduction in CPU idle usage since most threads are now sleeping. Also added useful log messages to `Peer::NetworkErrors` for easier debugging.
> Remove mutex protecting peer socket

- build/linux/Dockerfile
- build/macos/Dockerfile
- build/win64/Dockerfile
This will strip the symbols and compile with the optimisations turned on. Also use ubuntu 16.04 as the build base for Linux to cater for older libc versions.
> Make release binaries using dockerfiles

- src/kernel/blockchain.cpp
- src/kernel/schnorr.cpp
- src/kernel/schnorr.h
- tests/BlockchainTests.cpp
- tests/BlockchainTests.h
- tests/SchnorrTests.cpp
- tests/SchnorrTests.h
This PR implements MuSig schnorr signature aggregation for transactions. This allows for multiple schnorr inputs to be signed with a single signature. To sign a group of schnorr outputs with an aggregate signature, leave the data field of each schnorr input to be signed without a `signature` field except for one input where you instead include an `aggregateSignature`. 
The `aggregateSignature` takes the following form:
```
"aggregateSignature": {
"signs": [0, 3, 5],
"signature": <base64 encoded sig>
}
```
The `signs` field enumerates the outputs that this aggregate signature covers. They are indexed by ordering all the output IDs spent in the transaction from smallest to largest. Each schnorr output may be covered by at most one aggregate signature. 
The signed message payload is the …
> Signature aggregation in transactions

- src/kernel/merkletree.cpp
- src/kernel/merkletree.h
- tests/MerkletreeTests.cpp
- tests/MerkletreeTests.h
In order to support the pay-to-merkletree effort, i needed the merkletree class to support building and verifying merkle proofs. 
I added this to the merkletree class, introduced two new classes:
- *MerkleProof* holds the proof data, and can serialize/deserialize them to and from Json
- *MerkleRootNode* can be initialized with a precomputed hash in case of reading a merkletree back from a proof - the nodes where the hash was calculated from are not availble, so the root value is just set from the constructor. LeftVal() and RightVal() will return empty.
> Added the ability to create and verify merkle proofs

- Dockerfile
When running ckd inside the docker container on K320, it crashed when it encountered a transaction utilizing lua. This PR fixes that.
> Fixes Dockerfile for crash when running lua scripts

- src/kernel/network.cpp
This PR fixes a bug where the `version` field in `getpeerinfo` was blank.
> Set node version when polling it for information

- src/kernel/network.cpp
The recent refactoring of the network stack left out some mutex releases that led to deadlocks under certain error conditions.
> Fix bug where the network stack would deadlock for certain errors

- build/win64/Dockerfile
This PR changes the release build procedure for Windows to produce a shared DLL for Lua instead of a static library. This should fix a bug where the Windows binaries could not load lz4 and thus were unable to decompress and validate transaction scripts.
Related to #52 which was a manifestation of the same issue on Linux.
> Build Lua as a DLL on Windows because that's required to import lz4

- src/kernel/network.cpp
If a peer with a very small ping connected to `ckd` then the peer could become disconnected in another thread and the connection deleted before its initial info was committed to the database. That resulted in a segmentation fault in some cases where the connection was deleted in another thread and then subsequently used in the initialisation thread.  This PR locks the connection right after its creation and only releases it once the peer is fully set up. The PR also removes an unnecessary sleep call.
Fixes #57
> Lock the connection while we are initialising it

- src/kernel/network.cpp
The listener is in its own thread now so it should be blocking. Removing the sleep in #69 causes a busy wait without this change.
> Set listener to blocking so the incoming connections loop does not busy wait

- src/kernel/network.cpp
Loop the incoming connections handler every two seconds to check if `running` becomes false and quite the thread. This fixes a bug where `ckd` wouldn't quit.
> Use socket selector for incoming connections

- src/kernel/network.h
The dockerfile for the project requires the `functional` header in order to use an `std::function`
> Functional is required for some platforms

- src/client/wallet.cpp
When re-winding transactions in the case of a re-org in the wallet we re-added the utxos of inputs to the database if we were tracking the transaction, irrespective of whether the output contained a pubkey we owned. This could lead to a crash when the wallet is digesting blocks after a re-org as it tries to lookup a public key the wallet doesn't have.
> Only re-add the utxo to the wallet database if it has a publicKey we own

- src/client/cryptoserver.h
- src/client/rpcserver.cpp
- src/client/wallet.cpp
- src/client/wallet.h
This PR adds the `signmessage` RPC to `ckd`. Given a string and a public key for which the private key is stored in the wallet the RPC returns the signature for the message that will verify with the given public key.
> Add RPC for signing an arbitrary string with a given public key

- src/kernel/blockchain.cpp
- src/kernel/contract.cpp
- tests/ContractTests.cpp
- tests/ContractTests.h
Also added a regression test for this and cleaned up some leftover `cout` calls
> Only return if all contract outputs have been checked successfully

- src/client/multicoin.cpp
- src/kernel/consensus/PoW.cpp
- src/kernel/consensus/PoW.h
A number of users have reported not finding any blocks. This addition is to help determine if they're mining (but slowly), not mining at all, or something else more subtle is happening.
> Add logging to the PoW consensus module

- src/kernel/network.cpp
- src/kernel/networkpeer.cpp
Sometimes nodes get connected to themselves, or are unable to resolve IP addresses. In that case an IP address such as 127.0.0.1 or 0.0.0.0 might be sent, which will cause the remote peer to disconnect. Add a check for such IP addresses before adding them to the peers list to send with an info message. Also improved the log message for disconnecting a peer behaving in this way to display the offending malformed IP address.
> Don't send invalid IP addresses in info messages

- src/kernel/network.cpp
Previously defer was used here, but that did not account for attempting to delete the connection before defer is deconstructed. Therefore a deadlock was caused as to delete the connection a lock on it is required. Instead manually release the lock.
> Ensure connection lock is released before attempting to delete it

- src/kernel/contract.cpp
- src/kernel/contract.h
- tests/ContractTests.cpp
- tests/ContractTests.h
If a Lua script was being validated and exceeded the allowed memory the allocator would throw an exception causing `ckd` to crash. This PR catches the exception so the script validation function returns `false` which is the expected behaviour. Also add some unit tests to ensure the correct behaviour in the event of script execution errors.
> Catch script resource exceptions to prevent crashes

- src/kernel/blockchain.cpp
Because the mempool is not saved in the database, it can become inconsistent with the current state of the UTXO set. In this case, calculating the transaction fees can cause an exception to be thrown as some of the transaction in our unconfirmed set become invalid and their inputs are removed from the database. As a workaround, simply return a block with no transactions in it.
> Catch InvalidElementException when generating a new mining block
